# Generated by Django 4.0.1 on 2022-01-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_rename_short_name_category_shortname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='shortname',
            new_name='short_name',
        ),
    ]
