# Generated by Django 4.0.1 on 2022-01-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_options_rename_message_contact_messagge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='descripcion',
            new_name='description',
        ),
    ]
